-- Radiant Bloom schema bootstrap
-- Run with: supabase db push

begin;

create extension if not exists "uuid-ossp";
create extension if not exists "pgcrypto";

create schema if not exists salon;

create or replace function public.set_current_timestamp()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc'::text, now());
  return new;
end;
$$;

create table if not exists salon.services (
  id uuid primary key default gen_random_uuid(),
  slug text generated always as (lower(regexp_replace(name, '\s+', '-', 'g'))) stored,
  name text not null,
  description text,
  duration_minutes integer not null check (duration_minutes > 0),
  price_cents integer not null check (price_cents >= 0),
  active boolean not null default true,
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone('utc'::text, now())
);

create trigger set_timestamp_services
before update on salon.services
for each row
execute procedure public.set_current_timestamp();

create table if not exists salon.staff (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid not null references auth.users (id) on delete cascade,
  display_name text not null,
  bio text,
  avatar_url text,
  active boolean not null default true,
  created_at timestamp with time zone not null default timezone('utc'::text, now())
);

create table if not exists salon.staff_services (
  staff_id uuid not null references salon.staff(id) on delete cascade,
  service_id uuid not null references salon.services(id) on delete cascade,
  primary key (staff_id, service_id)
);

create table if not exists salon.availability_blocks (
  id uuid primary key default gen_random_uuid(),
  staff_id uuid not null references salon.staff(id) on delete cascade,
  starts_at timestamp with time zone not null,
  ends_at timestamp with time zone not null,
  kind text not null default 'shift' check (kind in ('shift','break','away')),
  notes text,
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  check (starts_at < ends_at)
);

create table if not exists salon.bookings (
  id uuid primary key default gen_random_uuid(),
  confirmation_code text not null unique,
  public_token uuid not null default gen_random_uuid(),
  service_id uuid not null references salon.services(id),
  staff_id uuid references salon.staff(id),
  customer_full_name text not null,
  customer_email text not null,
  customer_phone text,
  customer_notes text,
  start_time timestamp with time zone not null,
  end_time timestamp with time zone not null,
  status text not null default 'pending' check (status in ('pending','confirmed','completed','cancelled')),
  created_at timestamp with time zone not null default timezone('utc'::text, now()),
  updated_at timestamp with time zone not null default timezone('utc'::text, now())
);

create trigger set_timestamp_bookings
before update on salon.bookings
for each row
execute procedure public.set_current_timestamp();

create table if not exists salon.booking_notes (
  id uuid primary key default gen_random_uuid(),
  booking_id uuid not null references salon.bookings(id) on delete cascade,
  author_id uuid references salon.staff(id),
  note text not null,
  created_at timestamp with time zone not null default timezone('utc'::text, now())
);

create table if not exists salon.notification_log (
  id bigint generated by default as identity primary key,
  booking_id uuid references salon.bookings(id) on delete set null,
  event_type text not null,
  recipient text not null,
  payload jsonb,
  status text not null default 'queued',
  created_at timestamp with time zone not null default timezone('utc'::text, now())
);

comment on table salon.services is 'Service catalog visible to shoppers and administrators.';
comment on table salon.staff is 'Salon staff connected to Supabase auth users for admin access.';
comment on table salon.bookings is 'Customer bookings sourced from HTMX forms.';

commit;

